version: "3.8"

services:
  dashboard_vendas:
    image: dashboard-vendas:latest
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.dashboard_vendas.rule=Host(`dashboard.arvsystems.cloud`)
        - traefik.http.routers.dashboard_vendas.entrypoints=websecure
        - traefik.http.routers.dashboard_vendas.tls.certresolver=letsencryptresolver
        - traefik.http.services.dashboard_vendas.loadbalancer.server.port=8501
        - traefik.http.routers.dashboard_vendas.service=dashboard_vendas

networks:
  network_public:
    external: true
    name: network_public
